### ISSUE TITLE
Missing support for `btst dN,#immed`

### ISSUE THREAD

**Issue by flamewing** [grahambates/68kcounter#1]
There is one curious edge case in the original 68k: it can run this instruction:

```68k
btst dN,#immed
```

It is the only instruction which accepts an immediate as destination. Like other memory addressing modes, it is modulo 8 bits. The cycle counter currently does not support it. Older versions of the PRM do not list it, but more recent ones do. It is also worth noting that there is another edge case related to this instruction: [it reuses microcode](http://gendev.spritesmind.net/forum/viewtopic.php?t=2917) from the `btst dn,dm` case, and hence, its timing is a base of 6(1/0)+<ea> *instead of* the expected 4(1/0)+<ea>.

I haven't double-checked cycle counts from other instructions, but there are a few cases where the official manual is known to be wrong; if you want a table with the best known times, you can check [this document](https://gist.github.com/flamewing/af3b0863570afe317518eff849f58689), a slightly reformatted mirror.

**Comment by grahambates** [comment]
Thanks for pointing that out. That reference document is really useful, I wish I'd found it earlier! I'll cross reference my table with that when I get a chance.
