### ISSUE TITLE
Cycle counts wrong/unsupported for some instructions

### ISSUE THREAD

**Issue by flamewing** [grahambates/68kcounter#2]
I created a [large file](https://gist.github.com/flamewing/73973a94eaf3d24197db5e1080c6a56e) for testing this extension. It contains every instruction and addressing mode from the original MC68000, as well as cycle counts obtained from [the file](https://gist.github.com/flamewing/af3b0863570afe317518eff849f58689) I mentioned in another issue.

I found a few errors on the given cycle counts:

* all `addi/subi` instructions of byte and word size with data register direct addressing mode are off by 0(0/1).
* all `addi/subi` instructions of byte and word size for all other addressing modes are off by 4(1/0).
* `andi.l` is off by 0(0/1) for all addressing modes except data register direct.
* `eori` instructions of byte and word size for all addressing modes except data register direct are off by 0(1/1).
* `eori/ori` instruction is not supported at all (showing no cycle/sizes at all) except on their `eor/or` forms, which assemblers translate into `eori/or` for the binary. This includes `eori/ori` to `ccr/sr`.
*  `andi/ori` to `sr/ccr` are off by 4(2/1).
*  `eori` to `sr/ccr` is off by 4(1/0).
* `btst.b d0,#immed` is not supported; it should be 2 words and 10(2/0).
* all `move` to `sr/ccr` are off by 4(2/1).
* `tas.b d0` is off by 0(0/1).
* `tas.b (xxx).w` and `tasb. (xxx).l` are off by 0(1/0).
* `move` to/from `usp` are off by a lot; they should be 1 word 4(1/0).
* `reset` is off by a lot; it should be 1 word 132(1/0).
* `trapv` is off by 0(1/3).
* `illegal` is not supported; it should be 1 word 34(4/3).
* all `addq/subq` instructions of byte and word size with addressing modes other than data/address register direct are off by 0(0/1).
* `dbhs` (alias of `dbcc`) and `dbls` are not supported. They should match other `dbCC` instructions.
* `st/sf/shs/slo/sls` are not supported (`shs` is an alias to `scc`, and `slo` is an alias of `scs`). They should match other `sCC` instructions.
* `bhs/bls/bvc/bvs` are not supported; `bhs` is an alias of `bcc`. They should match other `bCC` instructions.
* for `divu/divs/mulu/muls` (other than immediate forms of `mulu/muls`) maybe a range of cycles, or the average, would work better than the worst case possible.
* 
* `muls` formula used for immediate addressing mode seems to be wrong. A faster and simpler way to compute it is 38(1/0)+`<ea>`+2*m(0/0), with `m = popcount((src ^ (src << 1)) & 0xFFFF)`.
* `add/sub` for byte and word immediate modes are off by 0(0/1).
* `asl/asr/lsl/lsr/rol/ror/roxl/roxr` with immediate operands should probably give more accurate cycle counts based on the number of bit shifts. For other addressing modes, it might be better to give a range or an average.

I haven't checked the word counts, but I would not be surprised if they are also wrong.

**Comment by grahambates** [comment]
Thanks for your work putting this together. This would be ideal for converting into a comprehsive suite of unit tests.

Some of the unsupported stuff I was aware of, but there's plenty that needs investigating. I'll get cracking on it!

**Comment by grahambates** [comment]
I'm looking at `MULU`/`MULS` now and I've found an inconsistency between the file and the timings given in `yacht.txt`:

```
mulu.w	#i16,d0							; 38+2m(1/0) +  8(2/0) =
```
vs
```
------------------------------------------------------------------------------- 
                  |    Exec Time    |               Data Bus Usage              
    MULU,MULS     |  INSTR     EA   |  1st OP (ea)  |          INSTR            
------------------+-----------------+---------------+-------------------------- 
<ea>,Dn :        /                  |               |                           
  .W :          /                   |               |                           
  ... 
    #<data>    | 38+2m(1/0)  4(1/0) |      np       |               np       n* 
```

Is this a deliberate change that I need to be aware of or an error?

**Comment by flamewing** [comment]
Oh, sorry, that was a mistake. I also don't know why my cycle adder script missed mulu and muls instructions; anyway, I updated the file with the corrections.

**Comment by grahambates** [comment]
All cycle counts are looking good now with automated tests against your sample file. Thanks again for your help on this.
