### ISSUE TITLE
Web based version no longer works

### ISSUE THREAD

**Issue by matthiesenj** [grahambates/68kcounter#4]
See screenshot...

![image](https://github.com/grahambates/68kcounter/assets/21193062/040be8a1-6951-41ce-97de-cf16ff221415)

**Comment by grahambates** [comment]
Hiya, thanks for reporting this. There's a couple of things going on here:
- Like most assemblers, the parser requires that instructions have whitespace in front of them. If you add one or more spaces or tabs before `move` it does work
- The error handling for this looks to be broken. I'm not too sure why there's a random bit of HTML visible, but I'll sort it.

**Comment by matthiesenj** [comment]
Thanks.. yeah, the random html threw me off in such a way that I forgot all about asm statements needing indentation :-)
